media: 
  input: source/img
  output: img

content:
  - name: pages
    label: Pages
    path: site/test.md
    type: collection
    fields:
      - { name: image, label: Picture, type: image }
      - { name: body, label: Page Text, type: rich-text }
