media: 
  input: source/img
  output: img

content:
  - name: pages
    label: Pages
    path: source
    type: collection
    view:
      fields: [title]
    fields:
      - { name: title, label: Title, type: string, options: { maxlength: 36 } }
      - { name: body, label: Page Text, type: rich-text }
      - { name: banner, label: Banner Image, type: image }
