media: 
  input: source/img
  output: img

content:
  - name: pages
    label: Pages
    path: source
    type: collection
    fields:
      - { name: title, label: Title, type: String }
      - { name: body, label: Page Text, type: rich-text }
      - { name: banner, label: Banner Image, type: image }
